version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana

  grafana-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - .:/app
    depends_on:
      - grafana
    restart: unless-stopped

volumes:
  grafana-storage: